local _, addonTable = ...

-- Returns details about which not hidden characters and guilds contain items
-- matching the item link.
--   itemLink: string
--   sameConnectedRealms: boolean
--   sameCurrentFaction: boolean
function Syndicator.API.GetInventoryInfo(itemLink, sameConnectedRealm, sameFaction)
  local success, key = pcall(Syndicator.Utilities.GetItemKey, itemLink)
  if not success then
    error("Bad item link. Try using one generated by a call to GetItemInfo.")
    return
  end

  return Syndicator.ItemSummaries and Syndicator.ItemSummaries:GetTooltipInfo(key, sameConnectedRealm == true, sameFaction == true)
end

Syndicator.API.GetInventoryInfoByItemLink = Syndicator.API.GetInventoryInfo

-- Returns details about which not hidden characters and guilds contain items
-- matching the item ID (does not work for battle pet cages).
--   itemID: number
--   sameConnectedRealms: boolean
--   sameCurrentFaction: boolean
function Syndicator.API.GetInventoryInfoByItemID(itemID, sameConnectedRealm, sameFaction)
  local key = Syndicator.Utilities.GetItemKeyByItemID(itemID)
  return Syndicator.ItemSummaries and Syndicator.ItemSummaries:GetTooltipInfo(key, sameConnectedRealm == true, sameFaction == true)
end

-- Returns currency counts for a specific currency on all characters
--   currencyID: number
--   sameConnectedRealms: boolean
--   sameCurrentFaction: boolean
function Syndicator.API.GetCurrencyInfo(currencyID, sameConnectedRealm, sameFaction)
  assert(type(currencyID) == "number")
  return Syndicator.Tracking.GetCurrencyTooltipData(currencyID, sameConnectedRealm == true, sameFaction == true)
end

-- Set the callback used when an item's location is clicked in the /syns search results
-- callback: function(mode, entity, container, itemLink, searchText)
--    mode: "character" or "guild"
--    entity: Name of character or guild
--    container: "bag", "bank" or guild bank tab (number)
--    itemLink: Item Link for the item who's owner has been clicked on
--    searchText: Search text to help focus the item
function Syndicator.API.RegisterShowItemLocation(callback)
  addonTable.ShowItemLocationCallback = callback
end

local characters = {
  "Liadou",
  "Ninjoru",
  "Aamjo",
  "Lainka",
  "Zeilje",
  "Aaju",
  "Kochera",
  "Muton",
  "Rodjo",
  "Omro",
  "Mit",
  "Grakle",
  "Dexi",
  "Etetzienk",
  "Dengek",
  "Yvgilbikle",
  "Grovexi",
  "Nalgimi",
  "Gryshan",
  "Wezat",
}
local realms = {
  "Daggerspine",
  "Gnomeregan",
  "Moonrunner",
  "Scilla",
}
local guilds = {
  "Growlers",
  "Meowers",
  "Squeakers",
}
local characterMap = {}
local reverseCharacterMap = {}
local realmMap = {}
local guildMap = {}
local reverseGuildMap = {}

local function GenMap()
  local characterIndex = 0
  local realmIndex = 0
  local guildIndex = 0
  local sorted = GetKeysArray(SYNDICATOR_DATA.Characters)
  table.sort(sorted)
  for _, c in ipairs(sorted) do
    local data = SYNDICATOR_DATA.Characters[c]
    characterIndex = characterIndex + 1
    if data.details.realm and not realmMap[data.details.realm] then
      realmIndex = realmIndex + 1
      realmMap[data.details.realm] = realms[realmIndex]
    end
    if data.details.guild and not guildMap[data.details.guild] then
      guildIndex = guildIndex + 1
      guildMap[data.details.guild] = {fullName = guilds[guildIndex] .. realmMap[data.details.realm], guild = guilds[guildIndex], realm = realmMap[data.details.realm]}
      reverseGuildMap[guildMap[data.details.guild].fullName] = data.details.guild
    end
    characterMap[c] = {
      fullName = characters[characterIndex] .. "-" .. realmMap[data.details.realm],
      character = characters[characterIndex],
      realm = realmMap[data.details.realm],
      guild = data.details.guild and guildMap[data.details.guild].fullName,
    }
    reverseCharacterMap[characterMap[c].fullName] = c
  end
end

local frame = CreateFrame("Frame")
frame:RegisterEvent("PLAYER_LOGIN")
frame:SetScript("OnEvent", GenMap)

function Syndicator.API.GetAllCharacters()
  local result = GetKeysArray(SYNDICATOR_DATA.Characters)
  local newResult = {}
  for _, key in ipairs(result) do
    table.insert(newResult, characterMap[key].fullName)
  end
  return newResult
end

-- characterFullName: string, e.g. "Martin-NormalizedRealmName"
function Syndicator.API.GetByCharacterFullName(characterFullName)
  local c = SYNDICATOR_DATA.Characters[reverseCharacterMap[characterFullName] or characterFullName]
  if not c then
    return nil
  end
  c = CopyTable(c)
  Mixin(c.details, characterMap[characterFullName] or characterMap[reverseCharacterMap[characterFullName]])
  return c
end

Syndicator.API.GetCharacter = Syndicator.API.GetByCharacterFullName

function Syndicator.API.GetAllGuilds()
  local result = GetKeysArray(SYNDICATOR_DATA.Guilds)
  local newResult = {}
  for _, key in ipairs(result) do
    table.insert(newResult, guildMap[key].fullName)
  end
  return newResult
end

-- guildFullName: string, e.g. "The Jokesters-NormalizedRealmName"
function Syndicator.API.GetByGuildFullName(guildFullName)
  if SYNDICATOR_DATA.Guilds[reverseGuildMap[guildFullName] or guildFullName] then
    local g = CopyTable(SYNDICATOR_DATA.Guilds[reverseGuildMap[guildFullName] or guildFullName])
    Mixin(g.details, guildMap[reverseGuildMap[guildFullName]] or guildMap[guildFullName])
    return g, guildMap[guildFullName] and guildMap[guildFullName].fullName or guildFullName
  end
end

Syndicator.API.GetGuild = Syndicator.API.GetByGuildFullName

function Syndicator.API.GetWarband(index)
  index = index or 1
  return SYNDICATOR_DATA.Warband[index]
end

function Syndicator.API.GetCurrentCharacter()
  return Syndicator.BagCache and characterMap[Syndicator.BagCache.currentCharacter].fullName
end

function Syndicator.API.GetCurrentGuild()
  return Syndicator.GuildCache and guildMap[Syndicator.GuildCache.currentGuild].fullName
end

function Syndicator.API.DeleteCharacter(characterFullName)
  assert(Syndicator.BagCache and characterFullName ~= Syndicator.BagCache.currentCharacter, "Cannot delete live character")
  local characterData = Syndicator.API.GetByCharacterFullName(characterFullName)

  if not characterData then
    error("Character does not exist")
  end

  SYNDICATOR_DATA.Characters[characterFullName] = nil

  local realmSummary = SYNDICATOR_SUMMARIES.Characters.ByRealm[characterData.details.realmNormalized]
  if realmSummary and realmSummary[characterData.details.character] then
    realmSummary[characterData.details.character] = nil
  end
  Syndicator.CallbackRegistry:TriggerEvent("CharacterDeleted", characterFullName)
end

function Syndicator.API.DeleteGuild(guildFullName)
  local guildData, guildFullName = Syndicator.API.GetByGuildFullName(guildFullName)
  assert(guildFullName == nil or not Syndicator.GuildCache or guildFullName ~= Syndicator.GuildCache.currentGuild, "Cannot delete current guild")

  if not guildData then
    error("Guild does not exist")
    return
  end

  SYNDICATOR_DATA.Guilds[guildFullName] = nil

  local realmSummary = SYNDICATOR_SUMMARIES.Guilds.ByRealm[guildData.details.realm or guildData.details.realms[1]] -- legacy guild format used realms
  if realmSummary and realmSummary[guildData.details.guild] then
    realmSummary[guildData.details.guild] = nil
  end
  Syndicator.CallbackRegistry:TriggerEvent("GuildDeleted", guildFullName)
end

function Syndicator.API.ToggleCharacterHidden(characterFullName)
  local characterData = Syndicator.API.GetByCharacterFullName(characterFullName)
  assert(characterData, "Character does not exist")
  characterData.details.show.inventory = not characterData.details.show.inventory
end

function Syndicator.API.ToggleGuildHidden(guildFullName)
  local guildData, guildFullName = Syndicator.API.GetByGuildFullName(guildFullName)
  assert(guildData, "Guild does not exist")
  guildData.details.show.inventory = not guildData.details.show.inventory
end

-- Returns if the tracking data is ready for use
function Syndicator.API.IsReady()
  return Syndicator.Tracking.isReady
end

function Syndicator.API.IsBagEventPending()
  return not Syndicator.BagCache or Syndicator.BagCache.isUpdatePending
end

function Syndicator.API.IsGuildEventPending()
  return not Syndicator.GuildCache or Syndicator.GuildCache.isUpdatePending
end

function Syndicator.API.GetSearchKeywords()
  return CopyTable(Syndicator.Search.GetKeywords())
end
